// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.CommandBase;
import java.util.function.DoubleSupplier;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.DriveTrain;
import frc.robot.subsystems.Gyro;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class TurnDegrees extends CommandBase {
    private double target;
    private boolean atTarget;
    private PIDController pid;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
        private DriveTrain m_driveTrain;
    private double m_angle;
    private double m_speed;
    private double MAX_TURN_SPEED= 1;
    private double MIN_TURN_SPEED = 0.25;
    private Gyro m_gyro;
    double kP = 0.05;
    double kI = 0;
    double kD = 0;
    private double TURN_ERROR=.5;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS


    public TurnDegrees(double angle, double speed, DriveTrain subsystem, Gyro gyro) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        atTarget = false;
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        m_angle = angle;
        m_speed = speed;
        m_gyro = gyro;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        m_driveTrain = subsystem;
        addRequirements(m_driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        PIDController pid = new PIDController(kP, kI, kD);
        m_gyro.setYaw(0);
        
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        //double l_speed = 0;
        //double error = m_angle - Math.abs(m_gyro.getYaw());
        
        pid.setTolerance(0.5);
        pid.setIntegratorRange(-0.1, 0.1);
        double tempTurn = pid.calculate(m_gyro.getYaw(),m_angle);
        MathUtil.clamp(tempTurn, -0.5, 0.5);
        m_driveTrain.turn(tempTurn);
        SmartDashboard.putNumber("Turn Speed", tempTurn);
        atTarget = pid.atSetpoint();
        
        /* l_speed = error * kP * m_speed;
        if(l_speed>MAX_TURN_SPEED){
            l_speed=MAX_TURN_SPEED;
        }
            
        if(l_speed < MIN_TURN_SPEED) {
            l_speed = MIN_TURN_SPEED;
        }
        if(l_speed<-MAX_TURN_SPEED){
            l_speed=-MAX_TURN_SPEED;
        }        
        m_driveTrain.turn(false, l_speed);
        if(error>=-TURN_ERROR && error<=TURN_ERROR){
            //Applying a band of -.5 to .5 degrees of slush in the turn target.
            atTarget=true;
        } */
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return atTarget;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
