// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public final class Constants {
    public static final class DriveConstants {
      public static final int kLeftMotor1Port = 0;
      public static final int kLeftMotor2Port = 1;
      public static final int kRightMotor1Port = 2;
      public static final int kRightMotor2Port = 3;

      public static final int kEncoderCPR = 1024;
      public static final double kWheelDiameterInches = 6;
      public static final double kEncoderDistancePerPulse =
          // Assumes the encoders are directly mounted on the wheel shafts
          (kWheelDiameterInches * Math.PI) / (double) kEncoderCPR;
  
      
  
      public static final double kStabilizationP = 1;
      public static final double kStabilizationI = 0.5;
      public static final double kStabilizationD = 0;
  
      public static final double kTurnP = 1;
      public static final double kTurnI = 0;
      public static final double kTurnD = 0;
  
      public static final double kMaxTurnRateDegPerS = 100;
      public static final double kMaxTurnAccelerationDegPerSSquared = 300;
  
      public static final double kTurnToleranceDeg = 5;
      public static final double kTurnRateToleranceDegPerS = 10; // degrees per second
    }
  
    public static final class OIConstants {
      public static final int kDriverControllerPort = 0;
      public static final int kOperatorControllerPort = 1;
    }

    public static final class IntakeConstants {
        public static final double kEjectSpeed = -0.7;
        public static final double kIntakeSpeed = 0.45;
        public static final int kSparkMaxCanID = 21;
    }

    public static final class GyroConstants{
        public static final boolean kGyroReversed = true;
        public static final int kGyroCanID = 8;
        public static final int kChargeLevelTolerance = 2;
    }

    public static final class ArmConstants{
        public static final int kPositionScoreLow = -151;
        public static final int kPositionScoreCubeHigh = -70;
    }
  }

